### ISSUE TITLE
Python library

### ISSUE THREAD

**Issue by andrewfam** [workbooks/client_lib#4]
Would it be possible to provide this library in python? Please I need it quick

**Comment by workbooks** [comment]
Andrew, did you create a Python library?

**Comment by d4rkd0s** [comment]
@andrewfam Can you provide feedback on this?

(adding tag to notify user)

**Comment by d4rkd0s** [comment]
@workbooks, @andrewfam did mention "Please I need it quick" in 2014. It's now 2017.
