### ISSUE TITLE
c# lib possible error in post_params

### ISSUE THREAD

**Issue by GTSageDev** [workbooks/client_lib#6]
From the console tracelistener: 
URl to connect: «https://secure.workbooks.com/accounting/invoices.api?_dc=389000?_limit[]=1&_select_columns[]=lock_version&_ff[]=id&_ft[]=eq&_fc[]=43851&api_key= (etc)

Surely that should be a "&" not a "?" before _limit[]
Same for most queries - the first real query parameter is therefore ignored!

Update: sample VB code:

```
Dim workbooks As WorkbooksApi.WorkbooksApi = LoginToWorkbooks(apikey)
Dim queryParams As New Dictionary(Of String, Object)
Dim response As WorkbooksApi.WorkbooksApiResponse
Dim endPoint As String

endPoint = "accounting/invoices"
queryParams.Add("_limit", 1)
queryParams.Add("_select_columns[]", "lock_version")
queryParams.Add("_ff[]", "id")
queryParams.Add("_ft[]", "eq")
queryParams.Add("_fc[]", 43851)
response = workbooks.assertGet(endPoint, queryParams, Nothing)
```

which gives this console output

```
ApiWrapper Information: 2 : URl to connect: «https://secure.workbooks.com/accounting/invoices.api?_dc=283000?_limit=1&_select_columns[]=lock_version&_ff[]=id&_ft[]=eq&_fc[]=43851&api_key=REMOV£D&client=api, »

```

**Comment by workbooks** [comment]
Should be resolved as of commit 952841457398e624b846e1ce04dd6d2c2e0c17ce
